# Generated by Django 4.1.6 on 2023-02-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/news/img/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
