# Generated by Django 4.1.6 on 2023-02-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0001_initial'),
        ('news', '0003_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemModules.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='news',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemModules.company', verbose_name='Компания'),
        ),
    ]
