# Generated by Django 4.1.6 on 2023-02-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0001_initial'),
        ('news', '0004_category_compant_news_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='compant',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='Цвет Bootstrap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemModules.company', verbose_name='Компания'),
        ),
    ]
