# Generated by Django 4.1.6 on 2023-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='record_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер записи'),
        ),
    ]
