# Generated by Django 4.1.6 on 2023-03-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0008_alter_propertiesbyuserbool_isbool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_comment_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование иконки')),
                ('suffix', models.CharField(blank=True, max_length=100, verbose_name='Тип файла')),
                ('icon_url', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на иконку')),
            ],
            options={
                'verbose_name': 'Иконки файлов',
                'verbose_name_plural': 'Иконки файлов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CommonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_record', models.IntegerField(default=0, verbose_name='ID записи')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название файла')),
                ('size', models.FloatField(default=0, verbose_name='Размер файла')),
                ('type', models.CharField(blank=True, max_length=20, verbose_name='Тип файла')),
                ('attached_file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файлы')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('icon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_common_files', to='common.fileicon', verbose_name='Иконка')),
                ('module_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_common_files', to='systemModules.module', verbose_name='Модуль')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
                'ordering': ['pk'],
            },
        ),
    ]
