# Generated by Django 4.1.6 on 2023-03-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_fileicon_commonfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonfiles',
            old_name='module_name',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='commonfiles',
            old_name='id_record',
            new_name='record_id',
        ),
    ]
