# Generated by Django 4.1.6 on 2023-03-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0008_alter_propertiesbyuserbool_isbool'),
        ('common', '0005_remove_commonfiles_name_remove_commonfiles_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfiles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_files_company', to='systemModules.company', verbose_name='Компания'),
        ),
    ]
