# Generated by Django 4.1.6 on 2023-02-12 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemModules', '0001_initial'),
        ('userInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('person_id', models.CharField(blank=True, default=0, max_length=30, verbose_name='ИИН')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рожения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Приступил к работе')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Образование')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Место работы')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Контактный телефон')),
                ('telephone_job', models.CharField(blank=True, max_length=30, verbose_name='Рабочий телефон')),
                ('skype', models.CharField(blank=True, max_length=30, verbose_name='Skype')),
                ('instagram', models.CharField(blank=True, max_length=30, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=30, verbose_name='LinkedIn')),
                ('facebook', models.CharField(blank=True, max_length=30, verbose_name='Facebook')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('website', models.CharField(blank=True, max_length=30, verbose_name='Веб-сайт')),
                ('quote', models.TextField(blank=True, max_length=500, verbose_name='Цитата для блога')),
                ('certificate', models.ManyToManyField(blank=True, related_name='sertificate', to='userInformation.certificate', verbose_name='Сертификат')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='systemModules.company', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department', to='userInformation.department', verbose_name='Департамент')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='userInformation.gender', verbose_name='Пол')),
                ('honor', models.ManyToManyField(blank=True, related_name='honor', to='userInformation.honor', verbose_name='Звания в компании')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobtitle', to='userInformation.jobtitle', verbose_name='Должность')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education', to='userInformation.status', verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
                'ordering': ['-created_date'],
            },
        ),
    ]
