# Generated by Django 4.1.6 on 2023-02-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0008_alter_propertiesbyuserbool_isbool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInformation', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала дня')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время завершение дня')),
                ('is_working', models.BooleanField(default=False, verbose_name='Работает')),
                ('is_ended', models.BooleanField(default=False, verbose_name='Завершен')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание опоздания')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startday_company', to='systemModules.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочий день',
                'ordering': ['-pk'],
            },
        ),
    ]
