# Generated by Django 4.1.6 on 2023-02-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInformation', '0004_startday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startday',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершение дня'),
        ),
        migrations.AlterField(
            model_name='startday',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала дня'),
        ),
    ]
