# Generated by Django 4.1.6 on 2023-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInformation', '0005_alter_startday_end_time_alter_startday_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startday',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время завершение дня'),
        ),
        migrations.AlterField(
            model_name='startday',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала дня'),
        ),
    ]
