# Generated by Django 4.1.6 on 2023-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInformation', '0006_alter_startday_end_time_alter_startday_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackingProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day_time', models.TimeField(blank=True, null=True, verbose_name='Время начала дня по регламенту')),
                ('end_day_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения дня по регламенту')),
                ('start_break_time', models.TimeField(blank=True, null=True, verbose_name='Время начала перерыва')),
                ('end_break_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения перерыва')),
                ('company', models.IntegerField(blank=True, default=0, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Время по регламенту',
                'verbose_name_plural': 'Время по регламенту',
            },
        ),
    ]
