# Generated by Django 4.1.6 on 2023-02-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0008_alter_propertiesbyuserbool_isbool'),
        ('userInformation', '0007_timetrackingproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrackingproperties',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_tracking_property_company', to='systemModules.company', verbose_name='Компания'),
        ),
    ]
