# Generated by Django 4.1.6 on 2023-02-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemModules', '0008_alter_propertiesbyuserbool_isbool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('title_tech', models.CharField(blank=True, max_length=100, verbose_name='Техническое наименование')),
                ('html_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет HTML')),
                ('css_color', models.CharField(blank=True, max_length=100, verbose_name='CSS класс')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_category_company', to='systemModules.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('title_tech', models.CharField(blank=True, max_length=100, verbose_name='Техническое наименование')),
                ('html_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет HTML')),
                ('css_color', models.CharField(blank=True, max_length=100, verbose_name='CSS класс')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_priority_company', to='systemModules.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритет',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('edate', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания проекта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления проекта')),
                ('photo', models.ImageField(blank=True, upload_to='media/projects/%Y/%m/%d', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='projectManagement.category', verbose_name='Категория')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_company', to='systemModules.company', verbose_name='Компания')),
                ('managers', models.ManyToManyField(blank=True, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='Руководители проекта')),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderators', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы проекта')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта')),
                ('priority_tasks', models.ManyToManyField(blank=True, related_name='priority_tasks', to='projectManagement.priority', verbose_name='Приоритеты для задач')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('title_tech', models.CharField(blank=True, max_length=100, verbose_name='Техническое наименование')),
                ('html_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет HTML')),
                ('css_color', models.CharField(blank=True, max_length=100, verbose_name='CSS класс')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_status_company', to='systemModules.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskApproveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_status', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статуса')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание статуса')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_approve_status_company', to='systemModules.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Статус исполенности задачи',
                'verbose_name_plural': 'Статус исполенности задачи',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('progress', models.IntegerField(blank=True, default=0, null=True, verbose_name='Прогресс')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Исполнено')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('edate', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('tdate', models.DateField(blank=True, null=True, verbose_name='Фактическая дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления задачи')),
                ('estimated_time', models.FloatField(blank=True, default=0, null=True, verbose_name='Оценочное время')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('co_executor', models.ManyToManyField(blank=True, null=True, related_name='co_executor', to=settings.AUTH_USER_MODEL, verbose_name='Со-исполнители')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_company', to='systemModules.company', verbose_name='Компания')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='projectManagement.tasks')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Priority', to='projectManagement.priority', verbose_name='Приоритет')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projectManagement.project', verbose_name='Проект')),
                ('related_tasks', models.ManyToManyField(blank=True, null=True, related_name='related_tasks_for', to='projectManagement.tasks', verbose_name='Связанные задачи')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='projectManagement.status', verbose_name='Стаус')),
                ('viewers', models.ManyToManyField(blank=True, null=True, related_name='viewers', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSelfCategoryDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('html_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_userself_category_dictionary_company', to='systemModules.company', verbose_name='Компания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_self_category_dictionary', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская категория справочник',
                'verbose_name_plural': 'Пользовательская категория справочник',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserSelfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_category', to='projectManagement.userselfcategorydictionary', verbose_name='Категория')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_userselfcategory_company', to='systemModules.company', verbose_name='Компания')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_category_task', to='projectManagement.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Пользовательская категория',
                'verbose_name_plural': 'Пользовательская категория',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('track_date', models.DateField(blank=True, verbose_name='Дата')),
                ('spent_time', models.FloatField(blank=True, default=0, null=True, verbose_name='Затраченное время')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_timetracking_company', to='systemModules.company', verbose_name='Компания')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Задача', to='projectManagement.tasks')),
            ],
            options={
                'verbose_name': 'Учет времени',
                'verbose_name_plural': 'Учет времени',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskChangeHistoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения задачи')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_change_history_action_company', to='systemModules.company', verbose_name='Компания')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_action_task', to='projectManagement.tasks', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_change_task_action', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сведения об изменении задачи',
                'verbose_name_plural': 'Сведения об изменении задачи',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(blank=True, max_length=100, verbose_name='Строка изменения')),
                ('first_value', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Первоначальное значение')),
                ('finish_value', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Конечное значение')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_change_history_company', to='systemModules.company', verbose_name='Компания')),
                ('task_change_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_change', to='projectManagement.taskchangehistoryaction', verbose_name='Сведения об изменении задачи')),
            ],
            options={
                'verbose_name': 'История изменения задачи',
                'verbose_name_plural': 'История изменения задачи',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskApproveStatusActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_sent_at', models.DateField(blank=True, null=True, verbose_name='Время исполнения задачи')),
                ('approve_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.taskapprovestatus', verbose_name='Статус исполненности задачи')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_approve_status_actions_company', to='systemModules.company', verbose_name='Компания')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Текущий статус исполненности задачи',
                'verbose_name_plural': 'Текущий статус исполненности задачи',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnswerByExecutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approve_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.taskapprovestatusactions', verbose_name='Статус исполненности задачи')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_answer_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_answer_by_executors_company', to='systemModules.company', verbose_name='Компания')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_answer', to='projectManagement.tasks', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Ответ исполнителя',
                'verbose_name_plural': 'Ответ исполнителя',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tasks',
            field=models.ManyToManyField(blank=True, related_name='status_tasks', to='projectManagement.status', verbose_name='Статусы для задач'),
        ),
    ]
