# Generated by Django 4.1.6 on 2023-02-24 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0008_alter_propertiesbyuserbool_isbool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelfSavedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_userself_saved_tasks_company', to='systemModules.company', verbose_name='Компания')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_saved_task', to='projectManagement.tasks', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_self_pk_saved_task', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненные записи',
                'verbose_name_plural': 'Сохраненные записи',
                'ordering': ['pk'],
            },
        ),
    ]
