# Generated by Django 4.1.6 on 2023-02-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_userselfsavedtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='projectManagement.tasks'),
        ),
    ]
