# Generated by Django 4.1.6 on 2023-03-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Задача', to='projectManagement.tasks'),
        ),
    ]
