# Generated by Django 4.1.6 on 2023-03-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0006_alter_timetracking_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Priority', to='projectManagement.priority', verbose_name='Приоритет'),
        ),
    ]
