# Generated by Django 4.1.6 on 2023-03-24 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectManagement', '0007_alter_tasks_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование позиции')),
                ('access_lvl', models.IntegerField(blank=True, default=0, null=True, verbose_name='Процент доступа')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Позиция в проекте',
                'verbose_name_plural': 'Позиция в проекте',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SkillQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Вопрос по навыку')),
            ],
            options={
                'verbose_name': 'Вопрос по навыку',
                'verbose_name_plural': 'Вопрос по навыку',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SkillQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ответ по вопросу навыка')),
            ],
            options={
                'verbose_name': 'Ответы по навыку',
                'verbose_name_plural': 'Ответы по навыку',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SkillUserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.project', verbose_name='Проект')),
                ('questions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_user_question', to='projectManagement.skillquestion', verbose_name='Вопросы')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_answer_user', to='projectManagement.skills', verbose_name='Навык')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_user_answer', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='skillquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='skill_question_answers', to='projectManagement.skillquestionanswers', verbose_name='Список ответов'),
        ),
        migrations.AddField(
            model_name='skillquestion',
            name='right_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.skillquestionanswers', verbose_name='Ответ к вопросу'),
        ),
        migrations.CreateModel(
            name='ProjectPositionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access', models.BooleanField(blank=True, default=False, null=True)),
                ('project_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.projectposition', verbose_name='Позиция')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_position_user', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ответы по навыку',
                'verbose_name_plural': 'Ответы по навыку',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='projectposition',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='project_position_skill', to='projectManagement.skills', verbose_name='Приоритеты для задач'),
        ),
    ]
