# Generated by Django 4.1.6 on 2023-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0009_skills_questions_alter_skillquestion_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectposition',
            options={'ordering': ['pk'], 'verbose_name': 'Skill Позиция в проекте', 'verbose_name_plural': ' Skill Позиция в проекте'},
        ),
        migrations.AlterModelOptions(
            name='projectpositionusers',
            options={'ordering': ['pk'], 'verbose_name': 'Skill Позиция пользователя в проекте', 'verbose_name_plural': 'Skill Позиция пользователя в проекте'},
        ),
        migrations.AlterModelOptions(
            name='skillquestion',
            options={'ordering': ['pk'], 'verbose_name': 'Skill Вопрос по навыку', 'verbose_name_plural': 'Skill Вопрос по навыку'},
        ),
        migrations.AlterModelOptions(
            name='skillquestionanswers',
            options={'ordering': ['pk'], 'verbose_name': 'Skill Ответы по навыку', 'verbose_name_plural': 'Skill Ответы по навыку'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['pk'], 'verbose_name': 'Skill Навыки', 'verbose_name_plural': 'Skill Навыки'},
        ),
        migrations.AlterModelOptions(
            name='skilluseranswers',
            options={'ordering': ['pk'], 'verbose_name': 'Skill Ответ сотрудника', 'verbose_name_plural': 'Skill Ответ сотрудника'},
        ),
        migrations.AlterField(
            model_name='projectposition',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='project_position_skill', to='projectManagement.skills', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='skillquestion',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Вопрос по навыку'),
        ),
        migrations.AlterField(
            model_name='skillquestionanswers',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ответ по вопросу навыка'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Навык'),
        ),
    ]
