# Generated by Django 4.1.6 on 2023-03-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0010_alter_projectposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilluseranswers',
            name='user_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.skillquestionanswers', verbose_name='Ответ к вопросу'),
        ),
    ]
