# Generated by Django 4.1.6 on 2023-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0011_skilluseranswers_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillquestion',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
