# Generated by Django 4.1.6 on 2023-02-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_dark_mode',
            field=models.ImageField(blank=True, upload_to='company/img/logotype/%Y/%m/%d', verbose_name='Логотип для темной версии'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_light_mode',
            field=models.ImageField(blank=True, upload_to='company/img/logotype/%Y/%m/%d', verbose_name='Логотип для светлой версии'),
        ),
        migrations.AddField(
            model_name='company',
            name='logotype',
            field=models.ImageField(blank=True, upload_to='company/img/logotype/%Y/%m/%d', verbose_name='Логотип компании'),
        ),
    ]
