# Generated by Django 4.1.6 on 2023-02-18 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemModules', '0002_company_logo_dark_mode_company_logo_light_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPropertiesByUserBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип свойства',
                'verbose_name_plural': 'Тип свойства',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PropertiesByUserBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(blank=True, null=True, verbose_name='Номер записи')),
                ('isBool', models.BooleanField(default=False, verbose_name='TrueFalse')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proerty_company', to='systemModules.company', verbose_name='Компания')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_module', to='systemModules.module', verbose_name='Модуль')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='systemModules.propertiesbyuserbool', verbose_name='Тип')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name': 'Свойства',
                'verbose_name_plural': 'Свойства',
                'ordering': ['user'],
            },
        ),
    ]
