# Generated by Django 4.1.6 on 2023-02-19 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemModules', '0003_typeofpropertiesbyuserbool_propertiesbyuserbool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesbyuserbool',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_company', to='systemModules.company', verbose_name='Компания'),
        ),
    ]
